version: "3.9"

services:

  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.8
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-public
      
  web:
    image: 'webdev'
    build: 
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: web-dev
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    labels:
      - traefik.enable=True
      - traefik.http.routers.reverse-proxy.rule=Host(`/`)
      - traefik.http.services.web.loadbalancer.server.port=8000
      - traefik.docker.network=traefik-public
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
