version: "3.9"
   
services:
  web:
    build: .
    #command: gunicorn progbasicas.wsgi:application --bind 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000 --settings=progbasicas.settings.dev
    volumes:
      - .:/code
    ports:
      - "8000:8000"