# Generated by Django 4.0 on 2022-08-03 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Er',
            fields=[
                ('nombre', models.CharField(choices=[('Z', 'Zidor'), ('KOS', 'Koskorrak'), ('KAS', 'Kaskondoak'), ('OIN', 'Oinarinak'), ('AZK', 'Azkarrak'), ('BID', 'Bidean'), ('AIN', 'Aingura'), ('CATE', 'Catecumenado')], max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rama',
            fields=[
                ('nombre', models.CharField(choices=[('Z2', 'Zidor 2'), ('Z3', 'Zidor 3'), ('KOS', 'Koskorrak'), ('KAS1', 'Kaskondoak 1'), ('KAS2', 'Kaskondoak 2'), ('OIN1', 'Oinarinak 1'), ('OIN2', 'Oinarinak 2'), ('AZK1', 'Azkarrak 1'), ('AZK2', 'Azkarrak 2'), ('BID1', 'Bidean 1'), ('BID2', 'Bidean 2'), ('AIN', 'Aingura'), ('CATE', 'Catecumenado')], default='Z2', max_length=100, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('er', models.ForeignKey(default='KAS', on_delete=django.db.models.deletion.CASCADE, to='documentation.er')),
            ],
        ),
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(choices=[(1, 'Primer'), (2, 'Segundo'), (3, 'Tercer')], default=1)),
                ('descripcion', models.TextField(blank=True, default='', null=True)),
                ('rama', models.ForeignKey(default='KAS1', on_delete=django.db.models.deletion.CASCADE, to='documentation.rama')),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('descripcion', models.TextField(null=True)),
                ('foto', models.ImageField(upload_to='')),
                ('rama', models.ForeignKey(default='Kaskondoak 1', on_delete=django.db.models.deletion.CASCADE, to='documentation.rama')),
            ],
        ),
        migrations.CreateModel(
            name='Simbolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(null=True)),
                ('foto', models.ImageField(upload_to='')),
                ('rama', models.ForeignKey(default='KAS1', on_delete=django.db.models.deletion.CASCADE, to='documentation.rama')),
            ],
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(null=True)),
                ('trimestre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documentation.trimestre')),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('descripcion', models.TextField(null=True)),
                ('foto', models.ImageField(upload_to='')),
                ('rama', models.ForeignKey(default='Kaskondoak 1', on_delete=django.db.models.deletion.CASCADE, to='documentation.rama')),
            ],
        ),
        migrations.CreateModel(
            name='Paso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('rama', models.OneToOneField(default='Kaskondoak 1', on_delete=django.db.models.deletion.CASCADE, to='documentation.rama')),
            ],
        ),
        migrations.CreateModel(
            name='Monte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('descripcion', models.TextField(null=True)),
                ('foto', models.ImageField(upload_to='')),
                ('rama', models.ForeignKey(default='Kaskondoak 1', on_delete=django.db.models.deletion.CASCADE, to='documentation.rama')),
            ],
        ),
        migrations.CreateModel(
            name='ContenidoRama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('rama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentation.rama')),
            ],
        ),
        migrations.CreateModel(
            name='Campamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('NA', 'Navidad'), ('SS', 'Semana Santa'), ('VE', 'Verano')], default='NA', max_length=2)),
                ('trimestre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documentation.trimestre')),
            ],
        ),
    ]
