# Generated by Django 4.0 on 2022-08-03 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trimestre',
            unique_together={('numero', 'rama')},
        ),
    ]
