# Generated by Django 4.0 on 2022-07-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='er',
            old_name='name',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='trimestre',
            name='numero',
            field=models.IntegerField(choices=[(1, 'Primero'), (2, 'Segundo'), (3, 'Tercero')], default=1),
        ),
    ]
