# Generated by Django 4.0 on 2022-09-01 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_alter_trimestre_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='trimestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documentation.trimestre'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
