# Generated by Django 4.0 on 2022-08-02 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_alter_rama_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='campamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentation.campamento'),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='paso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentation.paso'),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='rama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentation.rama'),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='trimestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentation.trimestre'),
        ),
        migrations.AlterField(
            model_name='trimestre',
            name='descripcion',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='trimestre',
            name='numero',
            field=models.IntegerField(choices=[(1, 'Primer'), (2, 'Segundo'), (3, 'Tercer')], default=1),
        ),
        migrations.AlterField(
            model_name='trimestre',
            name='rama',
            field=models.ForeignKey(default='KAS1', on_delete=django.db.models.deletion.CASCADE, to='documentation.rama'),
        ),
    ]
