# Generated by Django 4.0 on 2022-08-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0003_alter_contenido_campamento_alter_contenido_paso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
