# Generated by Django 4.0 on 2022-09-01 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0003_recurso_trimestre_alter_recurso_foto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurso',
            name='rama',
        ),
    ]
