# Generated by Django 4.0 on 2022-09-01 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0004_remove_recurso_rama'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='rama',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentation.rama'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='trimestre',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentation.trimestre'),
        ),
    ]
