# Generated by Django 4.0 on 2022-09-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0007_contenidocampa_contenidorama_contenidotrimestre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidorama',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
