# Generated by Django 4.0 on 2022-09-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0008_alter_contenidorama_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='rama',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
