version: "3.9"

services:
  web:
    image: progbasicas-web
    build: 
      context: ../../
      dockerfile: Dockerfile
    container_name: web
    env_file:
      - .env
    volumes:
      - ../../:/app
    command: ["bash", "./start-prod.sh"]
    labels:
      - traefik.enable=True
      - traefik.docker.network=traefik-public
      - traefik.http.routers.web.rule=Host(`${DOMAIN}`)
      - traefik.http.services.web.loadbalancer.server.port=8000
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true
