version: "3.9"

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.8
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      # Enable Docker in Traefik, so that it reads labels from Docker services
      - --providers.docker=true
      # Enable the access log, with HTTP requests
      - --accesslog
      # Enable the Traefik log, for configurations and errors
      - --log
      # Enable the Dashboard and API
      - --api
      # Enable the Dashboard and API in insecure mode for local development
      - --api.insecure=true
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-public
  
  web:
    image: progbasicas-web
    build: 
      context: ../../
      dockerfile: Dockerfile
      target: prod
    container_name: web
    env_file:
      - .env
    volumes:
      - ../../:/app
    ports:
      - "8000:8000"
    command: ["bash", "./start-prod.sh"]
    labels:
      - traefik.enable=True
      - traefik.http.routers.reverse-proxy.rule=Host(`/`)
      - traefik.http.services.web.loadbalancer.server.port=8000
      - traefik.docker.network=traefik-public
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
