# Generated by Django 4.0 on 2022-09-14 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Er',
            fields=[
                ('nombre', models.CharField(choices=[('Z', 'Zidor'), ('KOS', 'Koskorrak'), ('KAS', 'Kaskondoak'), ('OIN', 'Oinarinak'), ('AZK', 'Azkarrak'), ('BID', 'Bidean'), ('AIN', 'Aingura'), ('CATE', 'Catecumenado')], max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rama',
            fields=[
                ('nombre', models.CharField(choices=[('Z2', 'Zidor 2'), ('Z3', 'Zidor 3'), ('KOS', 'Koskorrak'), ('KAS1', 'Kaskondoak 1'), ('KAS2', 'Kaskondoak 2'), ('OIN1', 'Oinarinak 1'), ('OIN2', 'Oinarinak 2'), ('AZK1', 'Azkarrak 1'), ('AZK2', 'Azkarrak 2'), ('BID1', 'Bidean 1'), ('BID2', 'Bidean 2'), ('AIN', 'Aingura'), ('CATE', 'Catecumenado')], default='Z2', max_length=100, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('er', models.ForeignKey(default='KAS', on_delete=django.db.models.deletion.CASCADE, to='documentation.er')),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('descripcion', models.TextField(null=True)),
                ('foto', models.ImageField(upload_to='')),
                ('rama', models.ForeignKey(default='Kaskondoak 1', on_delete=django.db.models.deletion.CASCADE, to='documentation.rama')),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('descripcion', models.TextField(null=True)),
                ('foto', models.ImageField(upload_to='')),
                ('rama', models.ForeignKey(default='Kaskondoak 1', on_delete=django.db.models.deletion.CASCADE, to='documentation.rama')),
            ],
        ),
    ]
